# Generated by Django 5.0.3 on 2024-03-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_frontend', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('lang_pl', models.CharField(max_length=256)),
                ('lang_eng', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Frameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('LanguageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.languages')),
            ],
        ),
    ]
