# Generated by Django 5.0.3 on 2024-03-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_remove_frameworks_languageid_languagesframeworks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frameworks',
            old_name='LanguageId',
            new_name='languages',
        ),
    ]
