# Generated by Django 5.0.3 on 2024-04-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0003_rename_languageid_frameworks_languages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frameworks',
            options={'verbose_name_plural': 'frameworks'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='wording',
            options={'verbose_name': 'wording', 'verbose_name_plural': 'wording'},
        ),
    ]
