import { FRAMEWORKS as frameworks, LANGUAGES } from "../enums";

export const FRAMEWORKS: Record<frameworks, LANGUAGES[]> = {
  [frameworks.ANGULAR]: [LANGUAGES.TYPE_SCRIPT, LANGUAGES.JAVA_SCRIPT, LANGUAGES.HTML, LANGUAGES.CSS, LANGUAGES.SASS],
  [frameworks.DJANGO]: [LANGUAGES.PYTHON],
  [frameworks.DJANGO_REST]: [LANGUAGES.PYTHON],
  [frameworks.FLASK]: [LANGUAGES.PYTHON, LANGUAGES.HTML],
  [frameworks.REACT]: [LANGUAGES.JAVA_SCRIPT, LANGUAGES.TYPE_SCRIPT, LANGUAGES.CSS, LANGUAGES.HTML, LANGUAGES.SASS],
  [frameworks.REACT_NATIVE]: [LANGUAGES.JAVA_SCRIPT, LANGUAGES.TYPE_SCRIPT]
};
 