# Generated by Django 5.0.3 on 2024-03-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFrameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameworks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.frameworks')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.languages')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('repository_link', models.URLField(blank=True, null=True)),
                ('framework', models.ManyToManyField(through='projects.ProjectFrameworks', to='portfolio_api.frameworks')),
                ('language', models.ManyToManyField(through='projects.ProjectLanguages', to='portfolio_api.languages')),
            ],
        ),
        migrations.AddField(
            model_name='projectlanguages',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AddField(
            model_name='projectframeworks',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
    ]
